# ========================================================================================
#
#                                   Touch Grass
#                                 Default Config
#
# ========================================================================================

# Window Settings
[Window]
buttons_per_row = 2        # Set the number of buttons per row
column_spacing = 0         # Set space between buttons columns
row_spacing = 0            # Set space between buttons rows
#margin_all = 230          # Set margin around all buttons
margin_top = 400           # Set margin for top of buttons
margin_bottom = 400        # Set margin for bottom of buttons
margin_left = 700          # Set margin for left of buttons
margin_right = 700         # Set margin for right of buttons
show_binds = true          # Show keybinds on buttons


# Button Settings
[[Button]]
label = "lock"
action = "swaylock"
text = "Lock"
keybind = "l"
circular = true

[[Button]]
label = "shutdown"
action = "systemctl poweroff"
text = "Shutdown"
keybind = "s"
circular = true

[[Button]]
label = "logout"
action = "swaymsg exit"
text = "Logout"
keybind = "e"
circular = true

[[Button]]
label = "reboot"
action = "systemctl reboot"
text = "Reboot"
keybind = "r"
circular = true
